# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/db096f17-19b3-430e-b04c-5186edf90090";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EE22-9D0B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/second" =
    { device = "/dev/disk/by-uuid/255febbc-548f-4161-b05b-946b5844de48";
      fsType = "ext4";
    };

  fileSystems."/mnt/papernas" =
    { device = "192.168.1.14:/mnt/papernas/papershare";
      fsType = "nfs4";
      options = [ "x-systemd.automount" "noauto" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3a4dde37-8a8e-4b7d-bb4b-d9fec11ee757"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
