-- Generated by Monique - https://github.com/ToRvaLDz/monique

hl.monitor({
  output = "desc:LG Electronics LG ULTRAGEAR 407NTBK3M541",
  mode = "3840x2160@144",
  position = "4872x785",
  scale = 1.5,
  bitdepth = 10,
  cm = "srgb",
  sdrbrightness = 5,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Lenovo Group Limited T22i-20 V906L02M",
  mode = "1920x1080@60",
  position = "7432x428",
  scale = 1,
  transform = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:AOC 2369 ACLE59A000687",
  mode = "1920x1080@60",
  position = "2952x188",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Ancor Communications Inc VG248 G5LMQS102957",
  mode = "1920x1080@60",
  position = "2952x1268",
  scale = 1,
  cm = "srgb",
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
